/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin;

import UI.Inventario.*;
import Controladores.CProductos;
import Controladores.CReportes;
import com.toedter.calendar.JDateChooser;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author branp
 */
public class Reportes extends javax.swing.JDialog {

    private CReportes controlador = new CReportes();
    private String[] datos;
    private ArrayList<String> info;

    /**
     * Creates new form RellenarI
     */
    public Reportes(java.awt.Frame parent, boolean modal, String[] da) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        datos = da;
        jComboBoxReporte.addItem("Historial de descuentos");
        jComboBoxReporte.addItem("Top 10 ventas");
        jComboBoxReporte.addItem("Top 2 sucursales");
        jComboBoxReporte.addItem("Top 10 artículos");
        jComboBoxReporte.addItem("Top 10 clientes");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxReporte = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanelBuscar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooserFinal = new com.toedter.calendar.JDateChooser();
        jDateChooserInicio = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanelFondo.setBackground(new java.awt.Color(102, 204, 255));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setText("Reportes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(343, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(340, 340, 340))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 760, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 104, 760, 156));

        jComboBoxReporte.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jComboBoxReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxReporteActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 204, 255));
        jLabel3.setText("Fin:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, 28));

        jPanelBuscar.setBackground(new java.awt.Color(102, 204, 255));
        jPanelBuscar.setForeground(new java.awt.Color(255, 255, 255));
        jPanelBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBuscar.setEnabled(false);
        jPanelBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBuscarMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Buscar");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setEnabled(false);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelBuscarLayout = new javax.swing.GroupLayout(jPanelBuscar);
        jPanelBuscar.setLayout(jPanelBuscarLayout);
        jPanelBuscarLayout.setHorizontalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );
        jPanelBuscarLayout.setVerticalGroup(
            jPanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBuscarLayout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 40, 50, 30));
        jPanel2.add(jDateChooserFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 110, -1));

        jDateChooserInicio.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jDateChooserInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 110, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 204, 255));
        jLabel4.setText("Reporte:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 28));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 204, 255));
        jLabel6.setText("Inicio:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, 28));

        jPanelFondo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 760, 260));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanelFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 40, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jComboBoxReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxReporteActionPerformed
        jPanelBuscar.setEnabled(true);
        jLabel5.setEnabled(true);
    }//GEN-LAST:event_jComboBoxReporteActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        funcionamientoBoton();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jPanelBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBuscarMouseClicked
        funcionamientoBoton();
    }//GEN-LAST:event_jPanelBuscarMouseClicked

    public void funcionamientoBoton() {
        switch (jComboBoxReporte.getSelectedIndex()) {
            case 0:
                if (jDateChooserInicio.getDate() == null || jDateChooserFinal.getDate() == null) {
                    JOptionPane.showMessageDialog(null, "Por favor, selecciona ambas fechas.", "error", JOptionPane.ERROR_MESSAGE);
                } else if (jDateChooserInicio.getDate().after(jDateChooserFinal.getDate())) {
                    JOptionPane.showMessageDialog(null, "La fecha de inicio no puede ser posterior a la fecha de finalización.", "error", JOptionPane.ERROR_MESSAGE);
                } else {
                    // Formatear y mostrar las fechas en consola
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    String fechaInicio = dateFormat.format(jDateChooserInicio.getDate());
                    String fechaFin = dateFormat.format(jDateChooserFinal.getDate());
                    ArrayList<String> datosTabla = controlador.ReporteDescuentos(fechaInicio, fechaFin);
                    DefaultTableModel model = new DefaultTableModel();
                    model.addColumn("Numero de factura");
                    model.addColumn("Fecha");
                    model.addColumn("Nombre comprador");
                    model.addColumn("Nombre de caja");
                    model.addColumn("Nit");
                    model.addColumn("Total");
                    model.addColumn("Descuento");
                    model.addColumn("Total con descuento");
                    for (int i = 0; i < datosTabla.size(); i += 8) {
                        Object[] fila = {datosTabla.get(i), datosTabla.get(i + 1), datosTabla.get(i + 2), datosTabla.get(i + 3), datosTabla.get(i + 4), datosTabla.get(i + 5), datosTabla.get(i + 6), datosTabla.get(i + 7)};
                        model.addRow(fila);
                    }
                    jTable1.setModel(model);
                }
                break;
            case 1:
                if (jDateChooserInicio.getDate() == null || jDateChooserFinal.getDate() == null) {
                    JOptionPane.showMessageDialog(null, "Por favor, selecciona ambas fechas.", "error", JOptionPane.ERROR_MESSAGE);
                } else if (jDateChooserInicio.getDate().after(jDateChooserFinal.getDate())) {
                    JOptionPane.showMessageDialog(null, "La fecha de inicio no puede ser posterior a la fecha de finalización.", "error", JOptionPane.ERROR_MESSAGE);
                } else {
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    String fechaInicio = dateFormat.format(jDateChooserInicio.getDate());
                    String fechaFin = dateFormat.format(jDateChooserFinal.getDate());
                    ArrayList<String> datosTabla = controlador.ReporteTop10(fechaInicio, fechaFin);
                    DefaultTableModel model = new DefaultTableModel();
                    model.addColumn("Numero de factura");
                    model.addColumn("Fecha");
                    model.addColumn("Nombre comprador");
                    model.addColumn("Nombre de caja");
                    model.addColumn("Nit");
                    model.addColumn("Total con descuento");
                    for (int i = 0; i < datosTabla.size(); i += 8) {
                        Object[] fila = {datosTabla.get(i), datosTabla.get(i + 1), datosTabla.get(i + 2), datosTabla.get(i + 3), datosTabla.get(i + 4), datosTabla.get(i + 5), datosTabla.get(i + 6), datosTabla.get(i + 7)};
                        model.addRow(fila);
                    }
                    jTable1.setModel(model);
                }
                break;
            default:
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxReporte;
    private com.toedter.calendar.JDateChooser jDateChooserFinal;
    private com.toedter.calendar.JDateChooser jDateChooserInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBuscar;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
